name: "Terraform"

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

  # defaults:
  #   run:
  #     shell: bash
  #     working-directory: terraform

  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: "Install pre-reqs"
      run: |
        curl -SL "https://releases.hashicorp.com/terraform/1.2.9/terraform_1.2.9_linux_amd64.zip" --output terraform.zip
        unzip terraform.zip
        mv terraform /usr/local/bin
        terraform --version
        rm terraform.zip
    - name: "Install TFLint"
      run: |
        wget "https://github.com/terraform-linters/tflint/releases/download/v0.40.0/tflint_linux_amd64.zip"
        unzip tflint_linux_amd64.zip
        mv tflint /usr/local/bin
        rm tflint_linux_amd64.zip
